### PR TITLE
Upgrade to AspectJ 1.9.20.1

### PR DESCRIPTION
**Pull request by staniakm**

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
Thanks for the update, but any chances that you can add a respective unit test which fails without that version bumping?

**Comment by staniakm** [comment]
> Thanks for the update, but any chances that you can add a respective unit test which fails without that version bumping?

I'm looking for a way to unit test it but I don't see any tests that check if retry mechanism waits for some period of time before retry.

**Comment by artembilan** [comment]
Well, you showed one in the issue: https://github.com/spring-projects/spring-retry/issues/406.
Then I see that we have `EnableRetryTests.ExpressionService` which provides a config similar to what you show in the issue.
Perhaps that's from where you can start unit testing it.

Would be great to see how it fails for you, so then we might be able to even just adjust existing test (and its configuration) to fail.
If it is only about Kotlin, then yeah, we don't have choice unless just accept the fix as is.

**Comment by staniakm** [comment]
Nah, its also fails with java. Made the same test with spring java service. 

 Yeah, I have found this test `EnableRetryTests.ExpressionService`. Not yet sure how to calcualte elapsed time because now method execution finish really quick without consider delays defined by backoff.

**Comment by artembilan** [comment]
I'm not sure how is the timing is relevant to the failure you are claiming with AspectJ.

Any explanations in behavior difference before and after upgrade?

**Comment by staniakm** [comment]
I don't really know why aspectJ affect retry delay. But with version 2.0.* first retry wait delayExpresion time, but next one is not using multipliedExpression to calculate delay and still using delayExpresion. So, for example with delayExpression="500" and multiplier "2.0", delay between method execution will be 500 every time. With old verions 1.3+ or with upadted aspectJ, delay will use multiplier, so delays between next method executions will be 500, 1000, 2000...

I have found solution how to calculate time in unit tests using DummySleeper, but it looks like unit tests are not affected by aspectJ issu

**Comment by staniakm** [comment]
Release notes for aspectJ https://htmlpreview.github.io/?https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/README-1920.html
Ans issue rised in spring project https://github.com/spring-projects/spring-framework/issues/27761

**Comment by artembilan** [comment]
Well, this one:
```
	@Retryable(backoff = @Backoff(delayExpression = "500", multiplierExpression = "2.0"),
			maxAttempts = 4)
	public void toBeRetried() {
		throw new IllegalArgumentException("some exception");
	}
```
fails for me even with AspectJ `1.9.20.1`:
```
2023-12-12T15:08:13.985-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Retry: count=0
2023-12-12T15:08:13.987-05:00 DEBUG 22384 --- [    Test worker] o.s.r.backoff.ExponentialBackOffPolicy   : Sleeping for 500
2023-12-12T15:08:14.502-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Checking for rethrow: count=1
2023-12-12T15:08:14.502-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Retry: count=1
2023-12-12T15:08:14.502-05:00 DEBUG 22384 --- [    Test worker] o.s.r.backoff.ExponentialBackOffPolicy   : Sleeping for 500
2023-12-12T15:08:15.011-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Checking for rethrow: count=2
2023-12-12T15:08:15.011-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Retry: count=2
2023-12-12T15:08:15.011-05:00 DEBUG 22384 --- [    Test worker] o.s.r.backoff.ExponentialBackOffPolicy   : Sleeping for 500
2023-12-12T15:08:15.512-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Checking for rethrow: count=3
2023-12-12T15:08:15.512-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Retry: count=3
2023-12-12T15:08:15.512-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Checking for rethrow: count=4
2023-12-12T15:08:15.513-05:00 DEBUG 22384 --- [    Test worker] o.s.retry.support.RetryTemplate          : Retry failed last attempt: count=4
```
but if I do this:
```
  implementation 'org.springframework.retry:spring-retry:2.0.5-SNAPSHOT'
```
Then all is good.
Apparently you are facing the problem fixed in this issue: https://github.com/spring-projects/spring-retry/issues/397.

So, I guess we can accept your PR as just a dependency upgrade and that's it.
Just because the problem has nothing to do with AspectJ and the real fix for `delayExpression` is already in.

We are planning to release `2.0.5` this Friday.

**Comment by artembilan** [comment]
@staniakm ,

thank you for contribution; looking forward for more!

**Pull request merged**
