### PR TITLE
JDK17; Spring Framework 6.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by garyrussell**
Defer fetching RetryListener beans due to
`BeanCurrentlyInCreationException` with modern Spring Framework.

### CODE REVIEW

**Review by artembilan — CHANGES_REQUESTED** [review]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project spring-retry: Fatal error compiling: invalid target release: 17
```

Perhaps CI plan is not configured for Java 17.

**Review by artembilan — CHANGES_REQUESTED** [review]
I guess this one: https://github.com/spring-projects/spring-retry/blob/main/ci/images/ci-image/Dockerfile#L5
and so on to the https://github.com/spring-projects/spring-retry/blob/main/ci/images/get-jdk-url.sh

**Comment by garyrussell** [comment]
Still failing with these changes - I thought maybe I had to re-fly the pipeline, but...

```
% fly -t spring-retry set-pipeline -p spring-retry-2.0.x -c ci/pipeline.yml -l ci/parameters.yml
no changes to apply
```

**Comment by artembilan** [comment]
OK. Looks like I'm wrong.
Have no idea how this Concourse works 😄 .
We probably need an input from @snicoll .

Thanks

**Comment by garyrussell** [comment]
Maybe it only reads the scripts from main? (Rather than updates within the PR).

**Comment by garyrussell** [comment]
Yes; let's wait for @snicoll tomorrow.

**Comment by snicoll** [comment]
@garyrussell CI will run your PR against the current setup. It won't take any change to the CI pipeline itself as part of the PR. The reason for that is that the change you've made to the image in this PR needs a job to run to rebuild the docker image that the CI process uses to run the build. I'll review the changes above.

**Pull request closed without merging**
