### PR TITLE
#141, Fix memory leak when using @Retryable with beans having scope prototype.

### PR DESCRIPTION
**Pull request by russellfrancis**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@russellfrancis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=143)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=143) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@russellfrancis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=143)!

**Comment by mnisius** [comment]
I think someone should mention that this PR fixes the bug by removing caching at all. 

Do you guys have any numbers on how expensive this operation is? If caching is unnecessary why was it implemented in the first place.

**Comment by dsyer** [comment]
Yes, this PR simply disables caching. Closing in favour of #144.

**Pull request closed without merging**
