### PR TITLE
Memory leak when @Retryable is used on a @Scope("prototype") bean. #141

### PR DESCRIPTION
**Pull request by krolen**
Replaced hashmap with soft reference map

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@krolen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=144)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=144) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@krolen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=144)!

**Comment by dsyer** [comment]
Were you suggesting in #141 that we should only cache for scope=singleton? Maybe I missed it, but this is still caching everything? Or do you think that would be better now?

**Comment by dsyer** [comment]
Fixed in b279131. Also cherry picked to master: 54e1998

**Pull request closed without merging**
