### PR TITLE
#114 - Upgrade Spring to version 5.0.7

### PR DESCRIPTION
**Pull request by fabienmifsud**
#114

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@fabienmifsud Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=117)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=117) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fabienmifsud Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=117)!

**Comment by dsyer** [comment]
Sorry. Unintentional. AFAIK we aren’t using any APIs from Spring 5, so we ought to be safe to revert and release a new version. Downstream projects ought not to be affected?

**Comment by wilkinsona** [comment]
Hopefully not. I only noticed as the Platform build is grumpy because the 1.5.x-based Platform contains Framework 4.3 and Retry now uses 5.0.

**Comment by dsyer** [comment]
1.2.4 is out now

**Pull request merged**
