### PR TITLE
Move javax.annotation-api to jakarta

### LINKED ISSUE #227: Move javax.validation-api to jakarta
I have a spring-boot 2.4 app that includes spring-kafka which brings spring-retry.

Generated application jar is having duplicated validation-api jars due to spring-retry bringing javax.validation-api 1.3.2 while spring boot brings jakarta.validation-api 1.3.5

### PR DESCRIPTION
**Pull request by chicobento**
Fixes #227

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@chicobento Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=226)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=226) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@chicobento Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=226)!

**Comment by amarocco** [comment]
Hi is it planned to merge that change?

**Comment by dsyer** [comment]
It shouldn't actually affect any users since it's only there in a profile for building on Java 11. Does it matter otherwise?

**Comment by dsyer** [comment]
See ebc7200 for a different solution.

**Comment by chicobento** [comment]
Making optional works too. Will just double chekc once it gets in spring-kafka and boot.
Nit: why not move to jakarta as well ?

**Comment by dsyer** [comment]
> Nit: why not move to jakarta as well ?

No reason. Just trying not to change anything in a point release. Arguably this could already break some users, but the fix it easy, so I feel like it is justified.

**Pull request closed without merging**
