### PR TITLE
align default delay in code to value in document

### PR DESCRIPTION
**Pull request by ZhangChaoWN**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ZhangChaoWN Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=146)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=146) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ZhangChaoWN Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=146)!

**Comment by dsyer** [comment]
Maybe it would be better to change the javadocs (woiuldn't change the behaviour if someone is relying on it).

**Comment by ZhangChaoWN** [comment]
@dsyer you are correct, I revert my source code change, and add some content in javadoc to make the logic more clear

**Pull request closed without merging**
